### ISSUE TITLE
Why use RestSharp?

### ISSUE THREAD

**Issue by michaelstonis** [zuora/codelibrary-dotnet#2]
The defacto REST client for .Net is HttpClient. Why not utilize this for your library? It has a lot of benefits. The most notable is the fact that RestSharp development has essentially stalled out where HttpClient is actively supported and maintained by Microsoft. If you look at the last release of RestSharp, it came out over a year ago and their github shows that they are in a fairly dire situation. Additionally, HttpClient, if you are a .Net developer looking to use this library on different platforms, such as iOS or Android, there are major benefits to with using HttpClient. Using HttpClient would mean that consumers of this library would likely have a lower barrier for entry and an easier integration path.

**Comment by woocash** [comment]
We used what was provided by default with Swagger Codegen project, and that still uses RestSharp. Based on this discussion, someone was proposing an alternative, but it never got implemented:
https://github.com/swagger-api/swagger-codegen/issues/1889. Until Swagger Codegen supports this alternative library, we'll stick with what's out of the box.
